# Basic
title: Shaolin Liu
subtitle: Shaolin's personal blog
welcome_message: <a href="https://magical2world.github.io/blog.github.io/" target="_blank">Download the theme</a>
description: Welcome to my blog.
#creator: <a href="http://onev.cat">@onevcat</a>

#url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: magical2world
    github: magical2world
#    twitter:
#    gplus:
    mail: 13390100342@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
